name: flutter_kurdish_sorani_example
description: Example app for flutter_kurdish_sorani package
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_kurdish_sorani:
    path: ../  # This links to your package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 